# Generated by Django 4.1.4 on 2023-01-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Do_Kontaktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('skontaktowano', models.BooleanField(default=False)),
            ],
        ),
    ]
