# Generated by Django 4.1.4 on 2023-01-13 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]))]),
        ),
    ]
