# Generated by Django 4.1.4 on 2023-01-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplies', '0003_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Towar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('obecna_ilosc', models.IntegerField()),
                ('maksymalna_ilosc', models.IntegerField()),
            ],
        ),
    ]
