# Generated by Django 4.1.4 on 2023-01-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='towar',
            options={'verbose_name_plural': 'Towar'},
        ),
        migrations.AddField(
            model_name='towar',
            name='potrzeba_domówić',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='towar',
            name='maksymalna_ilosc',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='towar',
            name='obecna_ilosc',
            field=models.PositiveIntegerField(),
        ),
    ]
