# Generated by Django 4.1.4 on 2023-01-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cennik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zabieg',
            options={'verbose_name_plural': 'Zabiegi'},
        ),
    ]
