# Generated by Django 4.1.4 on 2023-01-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cennik', '0002_alter_zabieg_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabieg',
            name='czas_trwania',
        ),
    ]
