# Generated by Django 4.1.4 on 2023-01-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_date_appointment_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
