# Generated by Django 4.1.4 on 2023-01-16 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0005_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Wizyta',
        ),
        migrations.AlterModelOptions(
            name='wizyta',
            options={'verbose_name_plural': 'Wizyty'},
        ),
    ]
