# Generated by Django 4.1.4 on 2023-01-16 17:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0006_rename_appointment_wizyta_alter_wizyta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='day',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lekarz'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zabieg'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='time',
            field=models.CharField(choices=[('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM'), ('6:30 PM', '6:30 PM'), ('7 PM', '7 PM'), ('7:30 PM', '7:30 PM')], default='3 PM', max_length=10, verbose_name='Czas'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='time_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data rejestracji'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_article_set', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
